export const skills = [
  "JavaScript",
  "Python",
  "Leadership",
  "Product Management",
  "Machine Learning",
  "React",
  "Startup",
  "Data Science",
  "Career",
  "Marketing",
  "Product Design",
  "Agile",
  "SQL",
  "Growth",
  "Entrepreneurship",
  "UX Design",
  "HTML",
  "Design Thinking",
  "Strategy",
  "AWS",
  "CSS",
  "Backend",
  "Design",
  "Management",
  "Java",
  "Web Development",
  "Frontend",
  "User Research",
  "Software Engineering",
  "Project Management",
  "Coding",
  "Typescript",
  "Product",
  "Startups",
  "Deep Learning",
  "Interview",
  "UI Design",
  "Product Strategy",
  "User Experience",
  "Node",
  "DevOps",
  "Resume",
  "Digital Marketing",
  "Data",
  "Programming",
  "Business",
  "NodeJS",
  "Architecture",
  "Product Development",
  "Prototyping",
  "System Design",
  "SaaS",
  "Cloud",
  "Algorithms",
  "SEO",
  "Artificial Intelligence",
  "Analytics",
  "Web",
  "Interaction Design",
  "Data Structures",
  "Statistics",
  "Scrum",
  "UX Research",
  "Data Analysis",
  "Docker",
  "Sales",
  "Data Analytics",
  "Stakeholder Management",
  "User Interface Design",
  "TensorFlow",
  "Career Growth",
  "Kubernetes",
  "Web Design",
  "Engineering",
  "B2B",
  "Computer Vision",
  "Software Architecture",
  "User Interface",
  "Research",
  "Founder",
  "Fundraising",
  "Communication",
  "Branding",
  "Natural Language Processing",
  "Ruby",
  "Linux",
  "Git",
  "Product Marketing",
  "Redux",
  "Content Marketing",
  "Innovation",
  "Microservices",
  "Portfolio",
  "PyTorch",
  "Cybersecurity",
  "Android",
  "Consulting",
  "Visual Design",
  "Career Development",
  "PHP",
  "ReactJS",
  "AI",
  "Angular",
  "Business Development",
  "Golang",
  "Data Engineering",
  "GraphQL",
  "eCommerce",
  "C++",
  "Kotlin",
  "Public Speaking",
  "Graphic Design",
  "Operations",
  "Azure",
  "Keras",
  "Social Media",
  "Engineering Management",
  "Django",
  "Full Stack",
  "MySQL",
  "Technology",
  "Swift",
  "Blockchain",
];
